server:
  port: 8080

spring:
  application:
    name: bond-gateway
  cloud:
    gateway:
      routes:
        - id: bond-auth
          uri: lb://bond-auth
          predicates:
            - Path=/api/auth/**,/api/devices/**
        - id: bond-transfer
          uri: lb://bond-transfer
          predicates:
            - Path=/api/transfer/**,/api/workspaces/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
